import { createUseStrings, StringsDict } from "../createStrings";
import type {
  RecommendationCautionCode,
  RecommendationCompanion,
  RecommendationFitness,
  RecommendationReasonCode,
  RecommendationTravel,
  ScoredRoute,
} from "@/lib/routeRecommendation";

export type RecommendationCopy = {
  eyebrow: string; title: string; intro: string; locationScope: string; allCantons: string;
  time: string; fitness: string; companion: string; travel: string; returnConnection: string;
  nearbySearch: string; nearbyLocating: string; nearbyDenied: string; nearbyMode: string; manualMode: string;
  manualHint: string; placeOptional: string; placePlaceholder: string; placeSearching: string; placeNoResults: string;
  placeSelected: (place: string) => string; locationGroup: string; profileGroup: string; travelGroup: string;
  interestsGroup: string; interests: string; find: string; searching: string; noRoutes: string; error: string;
  bestMatch: string; why: string; themeArea: string; noThemeEvidence: string; noThemeMatch: string;
  alternatives: string; open: string; weather: string; conditions: string; transit: string; parking: string;
  dataUnavailable: { weather: string; conditions: string; transit: string; parking: string };
  values: { time: Record<number, string>; fitness: Record<RecommendationFitness, string>; companion: Record<RecommendationCompanion, string>; travel: Record<RecommendationTravel, string> };
  reason: Record<RecommendationReasonCode, (route: ScoredRoute) => string>;
  caution: Record<RecommendationCautionCode, string>;
};

type Locale = "de" | "gsw" | "fr" | "it" | "en" | "zh" | "es" | "pt" | "ru";

const L: Record<Locale, Omit<RecommendationCopy, "values" | "reason" | "caution">> = {
  de: { eyebrow:"Deine nächste Wanderung", title:"Was passt heute?", intro:"Sag uns kurz, wie dein Tag aussieht. SagaTrail wählt eine konkrete Route und zeigt dir offen, warum sie passt.", locationScope:"Suche aktuelle Routen in deiner Nähe per GPS", allCantons:"Standort nicht verfügbar – zeige Routen aus allen Kantonen", time:"Wie viel Zeit hast du?", fitness:"Wie viel möchtest du heute leisten?", companion:"Wer ist dabei?", travel:"Wie möchtest du anreisen?", returnConnection:"ÖV-Rückweg soll heute gut funktionieren", nearbySearch:"Nach meiner GPS-Position suchen", nearbyLocating:"Standort wird ermittelt …", nearbyDenied:"Standort nicht verfügbar – erlaube den Zugriff für die Suche in deiner Nähe.", nearbyMode:"In meiner Nähe", manualMode:"Ort eingeben", manualHint:"Wähle einen Ort für die Routensuche", placeOptional:"Suchort eingeben", placePlaceholder:"Ort, Gemeinde oder Region", placeSearching:"Orte werden gesucht …", placeNoResults:"Kein passender Ort gefunden", placeSelected:p=>`Suche nahe ${p}`, locationGroup:"Suchort", profileGroup:"Wegprofil", travelGroup:"Begleitung & Anreise", interestsGroup:"Interessen", interests:"Was möchtest du unterwegs sehen?", find:"Beste Route für heute finden", searching:"Route, Wetter, Bedingungen und Anreise werden verglichen …", noRoutes:"Keine Route passt gleichzeitig zu Zeit, Begleitung und Belastung. Versuche ein grösseres Zeitbudget.", error:"Die Empfehlung konnte gerade nicht geladen werden. Prüfe die Verbindung und versuche es erneut.", bestMatch:"Das ist heute deine beste Wahl", why:"Warum diese Route?", themeArea:"Themenbereich", noThemeEvidence:"Für diese Route ist noch kein Themenbeleg vorhanden.", noThemeMatch:"Keine Route mit deinen ausgewählten Themen passt gerade zu den übrigen Filtern.", alternatives:"Weitere passende Optionen", open:"Route ansehen", weather:"Wetter", conditions:"Wegbedingungen", transit:"ÖV-Rückweg", parking:"Parkplatz", dataUnavailable:{weather:"Wetter: keine Live-Daten",conditions:"Wegbedingungen: keine aktuelle Meldung",transit:"ÖV: keine Live-Daten für diesen Punkt",parking:"Parkplatz: keine Live-Daten"} },
  gsw: { eyebrow:"Dini nächschti Wanderig", title:"Was passt hüt?", intro:"Erzähl üs churz, wie dis Tag uusgseht. SagaTrail wählt e konkreti Route und zeigt dir, warum sie passt.", locationScope:"Suech aktuelli Route i diner Nöchi per GPS", allCantons:"Standort nöd verfügbar – zeig Route us allne Kantön", time:"Wie viel Zyt hesch?", fitness:"Wie viel wetsch hüt leiste?", companion:"Wer chunnt mit?", travel:"Wie wetsch aareise?", returnConnection:"ÖV-Rückwäg söll hüt guet funktioniere", nearbySearch:"Nach minere GPS-Position sueche", nearbyLocating:"Standort wird ermittelt …", nearbyDenied:"Standort nöd verfügbar – erlaub de Zugriff für d Suechi i diner Nöchi.", nearbyMode:"I miner Nöchi", manualMode:"Ort iigäh", manualHint:"Wähl en Ort für d Routensuechi", placeOptional:"Suechort iigäh", placePlaceholder:"Ort, Gmeind oder Region", placeSearching:"Ort werde gsuecht …", placeNoResults:"Kei passende Ort gfunde", placeSelected:p=>`Suech näbed ${p}`, locationGroup:"Suechort", profileGroup:"Wägprofil", travelGroup:"Begleitig & Aareis", interestsGroup:"Interesse", interests:"Was wetsch underwägs gseh?", find:"Beschti Route für hüt finde", searching:"Route, Wätter, Bedingige und Aareis werde vergliche …", noRoutes:"Kei Route passt gliichzytig zu Zyt, Begleitig und Belastig. Versuch es mit meh Zyt.", error:"D Empfehlig cha grad nöd glade werde. Prüef d Verbindig und versuechs nomal.", bestMatch:"Das isch hüt dini beschti Wahl", why:"Wieso die Route?", themeArea:"Themäbereich", noThemeEvidence:"Für die Route git s no kei Themänachwiis.", noThemeMatch:"Kei Route mit dine Themä passt grad zu de andere Filter.", alternatives:"Wiiteri passende Möglichkeit", open:"Route aluege", weather:"Wätter", conditions:"Wägbedingige", transit:"ÖV-Rückwäg", parking:"Parkplatz", dataUnavailable:{weather:"Wätter: kei Live-Date",conditions:"Wägbedingige: kei aktuelli Mäldig",transit:"ÖV: kei Live-Date für dä Punkt",parking:"Parkplatz: kei Live-Date"} },
  fr: { eyebrow:"Ta prochaine randonnée", title:"Qu'est-ce qui te convient aujourd'hui ?", intro:"Dis-nous comment se présente ta journée. SagaTrail choisit un itinéraire concret et t'explique pourquoi.", locationScope:"Chercher des itinéraires près de toi avec le GPS", allCantons:"Position indisponible – afficher les itinéraires de tous les cantons", time:"De combien de temps disposes-tu ?", fitness:"Quel effort souhaites-tu fournir ?", companion:"Qui t'accompagne ?", travel:"Comment veux-tu voyager ?", returnConnection:"Un retour en transports publics fiable est important aujourd'hui", nearbySearch:"Chercher près de ma position GPS", nearbyLocating:"Localisation en cours …", nearbyDenied:"Position indisponible – autorise l'accès pour chercher près de toi.", nearbyMode:"Près de moi", manualMode:"Saisir un lieu", manualHint:"Choisis un lieu pour chercher un itinéraire", placeOptional:"Saisir un lieu de recherche", placePlaceholder:"Ville, commune ou région", placeSearching:"Recherche de lieux …", placeNoResults:"Aucun lieu correspondant", placeSelected:p=>`Recherche près de ${p}`, locationGroup:"Zone de recherche", profileGroup:"Profil du sentier", travelGroup:"Accompagnement & trajet", interestsGroup:"Intérêts", interests:"Que veux-tu voir en chemin ?", find:"Trouver mon meilleur itinéraire", searching:"Comparaison des itinéraires, de la météo, des conditions et du trajet …", noRoutes:"Aucun itinéraire ne correspond au temps, au groupe et à l'effort. Essaie avec plus de temps.", error:"La recommandation n'a pas pu être chargée. Vérifie ta connexion et réessaie.", bestMatch:"Ton meilleur choix aujourd'hui", why:"Pourquoi cet itinéraire ?", themeArea:"Thème", noThemeEvidence:"Aucune preuve de thème n'est encore disponible pour cet itinéraire.", noThemeMatch:"Aucun itinéraire avec tes thèmes ne correspond aux autres filtres.", alternatives:"Autres options adaptées", open:"Voir l'itinéraire", weather:"Météo", conditions:"État du sentier", transit:"Retour en transports publics", parking:"Parking", dataUnavailable:{weather:"Météo : aucune donnée en direct",conditions:"Sentier : aucun rapport récent",transit:"Transports : aucune donnée en direct pour ce point",parking:"Parking : aucune donnée en direct"} },
  it: { eyebrow:"La tua prossima escursione", title:"Cosa fa per te oggi?", intro:"Raccontaci com'è la tua giornata. SagaTrail sceglie un percorso concreto e ti spiega perché.", locationScope:"Cerca percorsi vicino a te con il GPS", allCantons:"Posizione non disponibile – mostra percorsi di tutti i cantoni", time:"Quanto tempo hai?", fitness:"Quanto impegno vuoi metterci oggi?", companion:"Chi viene con te?", travel:"Come vuoi arrivare?", returnConnection:"Oggi è importante un rientro affidabile con i mezzi pubblici", nearbySearch:"Cerca vicino alla mia posizione GPS", nearbyLocating:"Rilevamento posizione …", nearbyDenied:"Posizione non disponibile – consenti l'accesso per cercare vicino a te.", nearbyMode:"Vicino a me", manualMode:"Inserisci un luogo", manualHint:"Scegli un luogo per cercare un percorso", placeOptional:"Inserisci una località", placePlaceholder:"Città, comune o regione", placeSearching:"Ricerca località …", placeNoResults:"Nessun luogo corrispondente", placeSelected:p=>`Cerca vicino a ${p}`, locationGroup:"Zona di ricerca", profileGroup:"Profilo del sentiero", travelGroup:"Compagnia & viaggio", interestsGroup:"Interessi", interests:"Cosa vuoi vedere lungo il percorso?", find:"Trova il percorso migliore", searching:"Confronto di percorsi, meteo, condizioni e trasporti …", noRoutes:"Nessun percorso soddisfa insieme tempo, compagnia e impegno. Prova con più tempo.", error:"Impossibile caricare il suggerimento. Controlla la connessione e riprova.", bestMatch:"La scelta migliore per oggi", why:"Perché questo percorso?", themeArea:"Tema", noThemeEvidence:"Non ci sono ancora prove del tema per questo percorso.", noThemeMatch:"Nessun percorso con i temi scelti soddisfa gli altri filtri.", alternatives:"Altre opzioni adatte", open:"Vedi percorso", weather:"Meteo", conditions:"Condizioni del sentiero", transit:"Rientro con i mezzi pubblici", parking:"Parcheggio", dataUnavailable:{weather:"Meteo: nessun dato in tempo reale",conditions:"Sentiero: nessuna segnalazione recente",transit:"Trasporti: nessun dato per questo punto",parking:"Parcheggio: nessun dato in tempo reale"} },
  en: { eyebrow:"Your next hike", title:"What fits today?", intro:"Tell us how your day looks. SagaTrail chooses one concrete route and explains why it fits.", locationScope:"Find current routes near you using GPS", allCantons:"Location unavailable – showing routes from all cantons", time:"How much time do you have?", fitness:"How much effort do you want today?", companion:"Who is joining?", travel:"How do you want to travel?", returnConnection:"A reliable public-transport return matters today", nearbySearch:"Search near my GPS position", nearbyLocating:"Getting your location …", nearbyDenied:"Location unavailable – allow access to search near you.", nearbyMode:"Near me", manualMode:"Enter a place", manualHint:"Choose a place for your route search", placeOptional:"Enter a search location", placePlaceholder:"Town, municipality or region", placeSearching:"Searching places …", placeNoResults:"No matching place found", placeSelected:p=>`Searching near ${p}`, locationGroup:"Search area", profileGroup:"Trail profile", travelGroup:"Company & travel", interestsGroup:"Interests", interests:"What would you like to see?", find:"Find my best route today", searching:"Comparing routes, weather, conditions and transport …", noRoutes:"No route fits the time, group and effort together. Try a larger time budget.", error:"The recommendation could not be loaded. Check your connection and try again.", bestMatch:"Your best choice today", why:"Why this route?", themeArea:"Theme area", noThemeEvidence:"No theme evidence is available for this route yet.", noThemeMatch:"No route with your selected themes currently matches the other filters.", alternatives:"Other good options", open:"View route", weather:"Weather", conditions:"Trail conditions", transit:"Return transport", parking:"Parking", dataUnavailable:{weather:"Weather: no live data",conditions:"Trail conditions: no current report",transit:"Public transport: no live data for this point",parking:"Parking: no live data"} },
  zh: { eyebrow:"你的下一次徒步", title:"今天适合什么？", intro:"告诉我们你今天的安排。SagaTrail 会选择一条具体路线并说明原因。", locationScope:"使用 GPS 查找附近路线", allCantons:"无法获取位置 – 显示所有州的路线", time:"你有多少时间？", fitness:"今天想挑战多大强度？", companion:"谁和你一起？", travel:"你想如何出行？", returnConnection:"今天需要可靠的公共交通返程", nearbySearch:"搜索我的 GPS 位置附近", nearbyLocating:"正在获取位置 …", nearbyDenied:"无法获取位置 – 请允许访问权限以搜索附近路线。", nearbyMode:"我附近", manualMode:"输入地点", manualHint:"选择路线搜索地点", placeOptional:"输入搜索地点", placePlaceholder:"城市、乡镇或地区", placeSearching:"正在搜索地点 …", placeNoResults:"未找到匹配地点", placeSelected:p=>`搜索 ${p} 附近`, locationGroup:"搜索区域", profileGroup:"步道特征", travelGroup:"同行与出行", interestsGroup:"兴趣", interests:"你想在途中看什么？", find:"寻找今天最适合的路线", searching:"正在比较路线、天气、路况和交通 …", noRoutes:"没有路线同时符合时间、同行者和强度。请尝试增加时间预算。", error:"无法加载推荐。请检查网络连接后重试。", bestMatch:"今天最适合你的选择", why:"为什么选择这条路线？", themeArea:"主题区域", noThemeEvidence:"这条路线暂时没有主题依据。", noThemeMatch:"没有路线同时符合所选主题和其他筛选条件。", alternatives:"其他合适选项", open:"查看路线", weather:"天气", conditions:"步道状况", transit:"返程交通", parking:"停车", dataUnavailable:{weather:"天气：没有实时数据",conditions:"路况：没有最新报告",transit:"公共交通：此地点没有实时数据",parking:"停车：没有实时数据"} },
  es: { eyebrow:"Tu próxima excursión", title:"¿Qué te apetece hoy?", intro:"Cuéntanos cómo es tu día. SagaTrail elige una ruta concreta y te explica por qué encaja.", locationScope:"Busca rutas actuales cerca de ti con GPS", allCantons:"Ubicación no disponible – mostrar rutas de todos los cantones", time:"¿Cuánto tiempo tienes?", fitness:"¿Cuánto esfuerzo quieres hacer hoy?", companion:"¿Quién te acompaña?", travel:"¿Cómo quieres desplazarte?", returnConnection:"Hoy importa tener un regreso fiable en transporte público", nearbySearch:"Buscar cerca de mi posición GPS", nearbyLocating:"Obteniendo tu ubicación …", nearbyDenied:"Ubicación no disponible – permite el acceso para buscar cerca de ti.", nearbyMode:"Cerca de mí", manualMode:"Introducir un lugar", manualHint:"Elige un lugar para buscar una ruta", placeOptional:"Introduce un lugar de búsqueda", placePlaceholder:"Ciudad, municipio o región", placeSearching:"Buscando lugares …", placeNoResults:"No se encontró ningún lugar coincidente", placeSelected:p=>`Buscar cerca de ${p}`, locationGroup:"Zona de búsqueda", profileGroup:"Perfil del sendero", travelGroup:"Compañía y transporte", interestsGroup:"Intereses", interests:"¿Qué te gustaría ver durante el camino?", find:"Encontrar mi mejor ruta", searching:"Comparando rutas, tiempo, condiciones y transporte …", noRoutes:"Ninguna ruta encaja a la vez con tiempo, grupo y esfuerzo. Prueba con más tiempo.", error:"No se pudo cargar la recomendación. Comprueba la conexión y vuelve a intentarlo.", bestMatch:"Tu mejor opción de hoy", why:"¿Por qué esta ruta?", themeArea:"Tema", noThemeEvidence:"Esta ruta aún no tiene evidencias de tema.", noThemeMatch:"Ninguna ruta con tus temas coincide con los demás filtros.", alternatives:"Otras opciones adecuadas", open:"Ver ruta", weather:"Tiempo", conditions:"Condiciones del sendero", transit:"Regreso en transporte público", parking:"Aparcamiento", dataUnavailable:{weather:"Tiempo: sin datos en directo",conditions:"Sendero: sin informe reciente",transit:"Transporte público: sin datos en este punto",parking:"Aparcamiento: sin datos en directo"} },
  pt: { eyebrow:"A tua próxima caminhada", title:"O que combina contigo hoje?", intro:"Conta-nos como é o teu dia. A SagaTrail escolhe uma rota concreta e explica porquê.", locationScope:"Encontrar rotas atuais perto de ti por GPS", allCantons:"Localização indisponível – mostrar rotas de todos os cantões", time:"Quanto tempo tens?", fitness:"Quanto esforço queres fazer hoje?", companion:"Quem vem contigo?", travel:"Como queres viajar?", returnConnection:"Hoje é importante ter um regresso fiável em transportes públicos", nearbySearch:"Pesquisar perto da minha posição GPS", nearbyLocating:"A obter a tua localização …", nearbyDenied:"Localização indisponível – permite o acesso para pesquisar perto de ti.", nearbyMode:"Perto de mim", manualMode:"Introduzir um local", manualHint:"Escolhe um local para pesquisar uma rota", placeOptional:"Introduzir local de pesquisa", placePlaceholder:"Cidade, município ou região", placeSearching:"A pesquisar locais …", placeNoResults:"Não foi encontrado nenhum local correspondente", placeSelected:p=>`Pesquisar perto de ${p}`, locationGroup:"Área de pesquisa", profileGroup:"Perfil do trilho", travelGroup:"Companhia e viagem", interestsGroup:"Interesses", interests:"O que gostarias de ver pelo caminho?", find:"Encontrar a melhor rota", searching:"A comparar rotas, meteorologia, condições e transportes …", noRoutes:"Nenhuma rota corresponde ao tempo, grupo e esforço. Tenta com mais tempo.", error:"Não foi possível carregar a recomendação. Verifica a ligação e tenta novamente.", bestMatch:"A tua melhor escolha hoje", why:"Porquê esta rota?", themeArea:"Tema", noThemeEvidence:"Ainda não há evidências de tema para esta rota.", noThemeMatch:"Nenhuma rota com os teus temas corresponde aos outros filtros.", alternatives:"Outras opções adequadas", open:"Ver rota", weather:"Meteorologia", conditions:"Condições do trilho", transit:"Regresso em transportes públicos", parking:"Estacionamento", dataUnavailable:{weather:"Meteorologia: sem dados em direto",conditions:"Trilho: sem relatório recente",transit:"Transportes públicos: sem dados neste ponto",parking:"Estacionamento: sem dados em direto"} },
  ru: { eyebrow:"Ваш следующий поход", title:"Что подходит сегодня?", intro:"Расскажите о своём дне. SagaTrail выберет маршрут и объяснит, почему он подходит.", locationScope:"Найти маршруты рядом с вами по GPS", allCantons:"Местоположение недоступно – показать маршруты всех кантонов", time:"Сколько у вас времени?", fitness:"Какую нагрузку вы хотите сегодня?", companion:"Кто идёт с вами?", travel:"Как вы хотите добраться?", returnConnection:"Сегодня важен надёжный обратный путь на общественном транспорте", nearbySearch:"Искать рядом с моей GPS-позицией", nearbyLocating:"Определяем местоположение …", nearbyDenied:"Местоположение недоступно – разрешите доступ для поиска рядом с вами.", nearbyMode:"Рядом со мной", manualMode:"Ввести место", manualHint:"Выберите место для поиска маршрута", placeOptional:"Введите место поиска", placePlaceholder:"Город, община или регион", placeSearching:"Ищем места …", placeNoResults:"Подходящее место не найдено", placeSelected:p=>`Ищем рядом с ${p}`, locationGroup:"Зона поиска", profileGroup:"Профиль тропы", travelGroup:"Компания и транспорт", interestsGroup:"Интересы", interests:"Что вы хотите увидеть по пути?", find:"Найти лучший маршрут", searching:"Сравниваем маршруты, погоду, условия и транспорт …", noRoutes:"Нет маршрута, подходящего по времени, группе и нагрузке. Попробуйте увеличить запас времени.", error:"Не удалось загрузить рекомендацию. Проверьте соединение и повторите попытку.", bestMatch:"Лучший выбор на сегодня", why:"Почему этот маршрут?", themeArea:"Тема", noThemeEvidence:"Для этого маршрута пока нет подтверждения темы.", noThemeMatch:"Нет маршрута, который с выбранными темами подходит по другим фильтрам.", alternatives:"Другие подходящие варианты", open:"Открыть маршрут", weather:"Погода", conditions:"Состояние тропы", transit:"Обратный транспорт", parking:"Парковка", dataUnavailable:{weather:"Погода: нет данных в реальном времени",conditions:"Тропа: нет свежих сообщений",transit:"Общественный транспорт: нет данных для этой точки",parking:"Парковка: нет данных в реальном времени"} },
};

const VALUE_DATA: Record<Locale, RecommendationCopy["values"]> = {
  de:{time:{90:"1½ Stunden",180:"3 Stunden",300:"5 Stunden"},fitness:{easy:"Locker",moderate:"Mittel",strong:"Anspruchsvoll"},companion:{solo:"Allein / Erwachsene",children:"Mit Kindern",wheelchair:"Mit Rollstuhl"},travel:{publicTransport:"ÖV",car:"Auto",flexible:"Offen"}},
  gsw:{time:{90:"1½ Stund",180:"3 Stund",300:"5 Stund"},fitness:{easy:"Locker",moderate:"Mittel",strong:"Aaspruchsvoll"},companion:{solo:"Allei / Erwachseni",children:"Mit Chind",wheelchair:"Mit Rollstuehl"},travel:{publicTransport:"ÖV",car:"Auto",flexible:"Offe"}},
  fr:{time:{90:"1 h 30",180:"3 heures",300:"5 heures"},fitness:{easy:"Facile",moderate:"Modéré",strong:"Exigeant"},companion:{solo:"Seul·e / adultes",children:"Avec des enfants",wheelchair:"En fauteuil roulant"},travel:{publicTransport:"Transports publics",car:"Voiture",flexible:"Ouvert"}},
  it:{time:{90:"1 ora e mezza",180:"3 ore",300:"5 ore"},fitness:{easy:"Facile",moderate:"Medio",strong:"Impegnativo"},companion:{solo:"Solo / adulti",children:"Con bambini",wheelchair:"In sedia a rotelle"},travel:{publicTransport:"Trasporto pubblico",car:"Auto",flexible:"Aperto"}},
  en:{time:{90:"1½ hours",180:"3 hours",300:"5 hours"},fitness:{easy:"Easy",moderate:"Moderate",strong:"Demanding"},companion:{solo:"Solo / adults",children:"With children",wheelchair:"With wheelchair"},travel:{publicTransport:"Public transport",car:"Car",flexible:"Open"}},
  zh:{time:{90:"1.5 小时",180:"3 小时",300:"5 小时"},fitness:{easy:"轻松",moderate:"中等",strong:"高强度"},companion:{solo:"独自 / 成人",children:"带孩子",wheelchair:"轮椅同行"},travel:{publicTransport:"公共交通",car:"汽车",flexible:"不限"}},
  es:{time:{90:"1½ horas",180:"3 horas",300:"5 horas"},fitness:{easy:"Fácil",moderate:"Moderado",strong:"Exigente"},companion:{solo:"Solo / adultos",children:"Con niños",wheelchair:"En silla de ruedas"},travel:{publicTransport:"Transporte público",car:"Coche",flexible:"Abierto"}},
  pt:{time:{90:"1½ horas",180:"3 horas",300:"5 horas"},fitness:{easy:"Fácil",moderate:"Moderado",strong:"Exigente"},companion:{solo:"Sozinho / adultos",children:"Com crianças",wheelchair:"Em cadeira de rodas"},travel:{publicTransport:"Transportes públicos",car:"Carro",flexible:"Aberto"}},
  ru:{time:{90:"1,5 часа",180:"3 часа",300:"5 часов"},fitness:{easy:"Легко",moderate:"Средне",strong:"Сложно"},companion:{solo:"Один / взрослые",children:"С детьми",wheelchair:"На коляске"},travel:{publicTransport:"Общественный транспорт",car:"Автомобиль",flexible:"Открыто"}},
};

const REASONS: Record<
  Locale,
  Record<RecommendationReasonCode, (route: ScoredRoute) => string>
> = {
  de:{time:r=>`passt in dein Zeitbudget von ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "passt zu deiner gewünschten Belastung",companion:()=> "passt zu deiner Begleitung",interest:()=> "trifft mindestens eines deiner Themen",nearby:()=> "liegt in deiner Nähe",season:()=> "ist für die aktuelle Saison eingeordnet",weather:()=> "das aktuelle Wetter spricht dafür",conditions:()=> "die aktuellen Wegbedingungen sprechen dafür",return:()=> "am Ziel gibt es passende ÖV-Abfahrten",arrival:()=> "der Start ist mit ÖV erreichbar",parking:()=> "am Start wurde ein Parkplatz gefunden"},
  gsw:{time:r=>`passt i dis Zytbudget vo ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "passt zu diner gewünschte Belastig",companion:()=> "passt zu diner Begleitig",interest:()=> "trifft mindestens eis vo dine Themä",nearby:()=> "liit i diner Nöchi",season:()=> "passt zur aktuelle Saison",weather:()=> "s aktuelle Wätter spricht defür",conditions:()=> "d aktuelle Wägbedingige spreche defür",return:()=> "am Ziel git s passende ÖV-Abfahrte",arrival:()=> "de Start isch mit ÖV erreichbar",parking:()=> "am Start isch en Parkplatz gfunde"},
  fr:{time:r=>`correspond à ton budget de ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "correspond à l'effort souhaité",companion:()=> "convient à ton accompagnement",interest:()=> "correspond à au moins un de tes thèmes",nearby:()=> "se trouve près de toi",season:()=> "est adapté à la saison actuelle",weather:()=> "la météo actuelle est favorable",conditions:()=> "les conditions actuelles sont favorables",return:()=> "des départs adaptés sont disponibles à l'arrivée",arrival:()=> "le départ est accessible en transports publics",parking:()=> "un parking a été trouvé au départ"},
  it:{time:r=>`rientra nel tuo budget di ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "corrisponde all'impegno scelto",companion:()=> "è adatto alla tua compagnia",interest:()=> "incontra almeno uno dei tuoi temi",nearby:()=> "è vicino a te",season:()=> "è adatto alla stagione attuale",weather:()=> "il meteo attuale è favorevole",conditions:()=> "le condizioni del sentiero sono favorevoli",return:()=> "all'arrivo ci sono partenze adatte",arrival:()=> "la partenza è raggiungibile con i mezzi pubblici",parking:()=> "alla partenza è stato trovato un parcheggio"},
  en:{time:r=>`fits your ${Math.round((r.route.minutes/60)*10)/10} h time budget`,fitness:()=> "matches your desired effort",companion:()=> "fits your group",interest:()=> "matches at least one of your themes",nearby:()=> "is near you",season:()=> "is suitable for the current season",weather:()=> "current weather supports it",conditions:()=> "current trail conditions support it",return:()=> "suitable departures are available at the destination",arrival:()=> "the start is reachable by public transport",parking:()=> "a parking place was found at the start"},
  zh:{time:r=>`符合你的 ${Math.round((r.route.minutes/60)*10)/10} 小时时间预算`,fitness:()=> "符合你想要的强度",companion:()=> "适合你的同行者",interest:()=> "至少符合一个主题",nearby:()=> "就在你附近",season:()=> "适合当前季节",weather:()=> "当前天气适合",conditions:()=> "当前路况适合",return:()=> "终点有合适的公共交通班次",arrival:()=> "起点可乘公共交通到达",parking:()=> "起点附近找到了停车位"},
  es:{time:r=>`encaja en tu presupuesto de ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "coincide con el esfuerzo elegido",companion:()=> "se adapta a tu compañía",interest:()=> "coincide con al menos uno de tus temas",nearby:()=> "está cerca de ti",season:()=> "es adecuado para la temporada actual",weather:()=> "el tiempo actual es favorable",conditions:()=> "las condiciones actuales son favorables",return:()=> "hay salidas adecuadas en el destino",arrival:()=> "se puede llegar al inicio en transporte público",parking:()=> "se encontró aparcamiento en el inicio"},
  pt:{time:r=>`cabe no teu orçamento de ${Math.round((r.route.minutes/60)*10)/10} h`,fitness:()=> "corresponde ao esforço escolhido",companion:()=> "é adequado para a tua companhia",interest:()=> "corresponde a pelo menos um dos teus temas",nearby:()=> "fica perto de ti",season:()=> "é adequado para a estação atual",weather:()=> "o tempo atual é favorável",conditions:()=> "as condições atuais são favoráveis",return:()=> "há partidas adequadas no destino",arrival:()=> "o início é acessível por transporte público",parking:()=> "foi encontrado estacionamento no início"},
  ru:{time:r=>`укладывается в ваш бюджет ${Math.round((r.route.minutes/60)*10)/10} ч`,fitness:()=> "соответствует выбранной нагрузке",companion:()=> "подходит вашей компании",interest:()=> "соответствует хотя бы одной теме",nearby:()=> "находится рядом с вами",season:()=> "подходит для текущего сезона",weather:()=> "текущая погода благоприятна",conditions:()=> "текущее состояние тропы благоприятно",return:()=> "в пункте назначения есть подходящие отправления",arrival:()=> "к началу можно добраться общественным транспортом",parking:()=> "у начала найдено место для парковки"},
};

const CAUTIONS: Record<
  Locale,
  Record<RecommendationCautionCode, string>
> = {
  de:{time:"liegt über deinem Zeitbudget",fitness:"ist für deine gewünschte Belastung anspruchsvoller",companion:"die Eignung für deine Begleitung ist nicht ideal",interest:"deine ausgewählten Themen sind dort nicht belegt",season:"ist saisonal weniger passend",weather:"das aktuelle Wetter verlangt Vorsicht",conditions:"es gibt aktuelle Hinweise zu den Wegbedingungen",return:"ÖV-Rückweg ist nicht zuverlässig belegt",arrival:"die ÖV-Anreise zum Start ist nicht zuverlässig bestätigt",nearby:"liegt weiter von deinem Standort entfernt"},
  gsw:{time:"liit über dim Zytbudget",fitness:"isch für dini Belastig anspruchsvoller",companion:"passt nöd ideal zu diner Begleitig",interest:"dini Themä sind det nöd belegt",season:"passt saisonal weniger",weather:"s aktuelle Wätter verlangt Vorsicht",conditions:"es git aktuelli Hiiwiis zu de Wägbedingige",return:"ÖV-Rückwäg isch nöd zuverlässig belegt",arrival:"d ÖV-Aareis zum Start isch nöd zuverlässig bestätigt",nearby:"liit wiiter vo dim Standort entfernt"},
  fr:{time:"dépasse ton budget de temps",fitness:"demande plus d'effort que prévu",companion:"convient moins bien à ton accompagnement",interest:"tes thèmes ne sont pas attestés ici",season:"est moins adapté à la saison",weather:"la météo actuelle invite à la prudence",conditions:"des informations concernent l'état du sentier",return:"le retour en transports publics n'est pas garanti",arrival:"l’accès au départ en transports publics n’est pas confirmé",nearby:"est plus éloigné de ta position"},
  it:{time:"supera il tuo budget di tempo",fitness:"richiede più impegno del previsto",companion:"è meno adatto alla tua compagnia",interest:"i tuoi temi non sono documentati qui",season:"è meno adatto alla stagione",weather:"il meteo attuale richiede prudenza",conditions:"ci sono avvisi sulle condizioni del sentiero",return:"il rientro con i mezzi pubblici non è garantito",arrival:"l’accesso al punto di partenza con i mezzi pubblici non è confermato",nearby:"è più lontano dalla tua posizione"},
  en:{time:"is over your time budget",fitness:"requires more effort than desired",companion:"is not an ideal fit for your group",interest:"your selected themes are not evidenced there",season:"is less suitable for the season",weather:"current weather calls for caution",conditions:"there are current trail-condition notices",return:"the public-transport return is not reliably confirmed",arrival:"public transport to the start is not reliably confirmed",nearby:"is farther from your location"},
  zh:{time:"超过了你的时间预算",fitness:"需要更高的强度",companion:"不太适合你的同行者",interest:"当地没有所选主题的依据",season:"不太适合当前季节",weather:"当前天气需要谨慎",conditions:"路况有最新提示",return:"公共交通返程缺乏可靠信息",arrival:"无法可靠确认公共交通是否可到达起点",nearby:"距离你的位置较远"},
  es:{time:"supera tu presupuesto de tiempo",fitness:"requiere más esfuerzo del deseado",companion:"no encaja del todo con tu compañía",interest:"tus temas no están documentados allí",season:"es menos adecuado para la temporada",weather:"el tiempo actual aconseja precaución",conditions:"hay avisos actuales sobre el sendero",return:"el regreso en transporte público no está confirmado",arrival:"no está confirmado que se pueda llegar al inicio en transporte público",nearby:"está más lejos de tu ubicación"},
  pt:{time:"ultrapassa o teu orçamento de tempo",fitness:"exige mais esforço do que o desejado",companion:"não é ideal para a tua companhia",interest:"os teus temas não estão comprovados aí",season:"é menos adequado à estação",weather:"o tempo atual exige prudência",conditions:"há avisos atuais sobre o trilho",return:"o regresso em transportes públicos não está garantido",arrival:"não está confirmado que seja possível chegar ao início por transportes públicos",nearby:"fica mais longe da tua localização"},
  ru:{time:"превышает ваш запас времени",fitness:"требует большей нагрузки",companion:"не идеально подходит вашей компании",interest:"выбранные темы там не подтверждены",season:"меньше подходит для сезона",weather:"текущая погода требует осторожности",conditions:"есть свежие сообщения о состоянии тропы",return:"надёжность обратного общественного транспорта не подтверждена",arrival:"возможность добраться до начала общественным транспортом не подтверждена",nearby:"находится дальше от вашего местоположения"},
};

const recommendationStrings = Object.fromEntries(
  (Object.keys(L) as Locale[]).map((locale) => [locale, { ...L[locale], values: VALUE_DATA[locale], reason: REASONS[locale], caution: CAUTIONS[locale] }]),
) as StringsDict<RecommendationCopy>;

export const useRecommendationStrings = createUseStrings(recommendationStrings);