import { LanguageCode } from "./languageCode";

type CantonTranslations = Record<LanguageCode, string>;

const CANTON_NAMES: Record<string, CantonTranslations> = {
  "Aargau":                    { de: "Aargau",                            gsw: "Aargau",                           fr: "Argovie",                           it: "Argovia",                 en: "Aargau",                       zh: "阿尔高",    es: "Argovia",                        pt: "Argóvia",                        ru: "Ааргау"                },
  "Appenzell Ausserrhoden":    { de: "Appenzell Ausserrhoden",            gsw: "Appezell Uusserrhode",             fr: "Appenzell Rhodes-Extérieures",      it: "Appenzello Esterno",      en: "Appenzell Outer Rhodes",       zh: "外阿彭策尔", es: "Appenzell Rodas Exteriores",    pt: "Appenzell Rodes Externas",       ru: "Аппенцелль-Ауссерроден"},
  "Appenzell Innerrhoden":     { de: "Appenzell Innerrhoden",             gsw: "Appezell Innerrhode",              fr: "Appenzell Rhodes-Intérieures",      it: "Appenzello Interno",      en: "Appenzell Inner Rhodes",       zh: "内阿彭策尔", es: "Appenzell Rodas Interiores",    pt: "Appenzell Rodes Internas",       ru: "Аппенцелль-Иннерроден" },
  "Basel-Landschaft":          { de: "Basel-Landschaft",                  gsw: "Baselbiet",                        fr: "Bâle-Campagne",                     it: "Basilea Campagna",        en: "Basel-Country",                zh: "巴塞尔乡村", es: "Basilea-Campo",                  pt: "Basileia-Campo",                 ru: "Базель-Ланд"           },
  "Basel-Stadt":               { de: "Basel-Stadt",                       gsw: "Basel-Schtadt",                    fr: "Bâle-Ville",                        it: "Basilea Città",           en: "Basel-City",                   zh: "巴塞尔城市", es: "Basilea-Ciudad",                 pt: "Basileia-Cidade",                ru: "Базель-Штадт"          },
  "Bern":                      { de: "Bern",                              gsw: "Bärn",                             fr: "Berne",                             it: "Berna",                   en: "Bern",                         zh: "伯尔尼",    es: "Berna",                          pt: "Berna",                          ru: "Берн"                  },
  "Freiburg":                  { de: "Freiburg",                          gsw: "Frybürg",                          fr: "Fribourg",                          it: "Friborgo",                en: "Fribourg",                     zh: "弗里堡",    es: "Friburgo",                       pt: "Friburgo",                       ru: "Фрибур"                },
  "Genf":                      { de: "Genf",                              gsw: "Genf",                             fr: "Genève",                            it: "Ginevra",                 en: "Geneva",                       zh: "日内瓦",    es: "Ginebra",                        pt: "Genebra",                        ru: "Женева"                },
  "Glarus":                    { de: "Glarus",                            gsw: "Glarus",                           fr: "Glaris",                            it: "Glarona",                 en: "Glarus",                       zh: "格拉鲁斯",   es: "Glaris",                         pt: "Glaris",                         ru: "Гларус"                },
  "Graubünden":                { de: "Graubünden",                        gsw: "Graubünde",                        fr: "Grisons",                           it: "Grigioni",                en: "Graubünden",                   zh: "格劳宾登",   es: "Grisones",                       pt: "Grisões",                        ru: "Граубюнден"            },
  "Jura":                      { de: "Jura",                              gsw: "Jura",                             fr: "Jura",                              it: "Giura",                   en: "Jura",                         zh: "汝拉",      es: "Jura",                           pt: "Jura",                           ru: "Юра"                   },
  "Luzern":                    { de: "Luzern",                            gsw: "Luzärn",                           fr: "Lucerne",                           it: "Lucerna",                 en: "Lucerne",                      zh: "卢塞恩",    es: "Lucerna",                        pt: "Lucerna",                        ru: "Люцерн"                },
  "Neuenburg":                 { de: "Neuenburg",                         gsw: "Neueburg",                         fr: "Neuchâtel",                         it: "Neuchâtel",               en: "Neuchâtel",                    zh: "纳沙泰尔",   es: "Neuchâtel",                      pt: "Neuchâtel",                      ru: "Невшатель"             },
  "Nidwalden":                 { de: "Nidwalden",                         gsw: "Nidwalde",                         fr: "Nidwald",                           it: "Nidvaldo",                en: "Nidwalden",                    zh: "下瓦尔登",   es: "Nidwalden",                      pt: "Nidwalden",                      ru: "Нидвальден"            },
  "Obwalden":                  { de: "Obwalden",                          gsw: "Obwalde",                          fr: "Obwald",                            it: "Obvaldo",                 en: "Obwalden",                     zh: "上瓦尔登",   es: "Obwalden",                       pt: "Obwalden",                       ru: "Обвальден"             },
  "Schaffhausen":              { de: "Schaffhausen",                      gsw: "Schaffhuse",                       fr: "Schaffhouse",                       it: "Sciaffusa",               en: "Schaffhausen",                 zh: "沙夫豪森",   es: "Schaffhausen",                   pt: "Schaffhausen",                   ru: "Шаффхаузен"            },
  "Schwyz":                    { de: "Schwyz",                            gsw: "Schwyz",                           fr: "Schwytz",                           it: "Svitto",                  en: "Schwyz",                       zh: "施维茨",    es: "Schwyz",                         pt: "Schwyz",                         ru: "Швиц"                  },
  "Solothurn":                 { de: "Solothurn",                         gsw: "Solothurn",                        fr: "Soleure",                           it: "Soletta",                 en: "Solothurn",                    zh: "索洛图恩",   es: "Soleura",                        pt: "Soleura",                        ru: "Золотурн"              },
  "St. Gallen":                { de: "St. Gallen",                        gsw: "St. Galle",                        fr: "Saint-Gall",                        it: "San Gallo",               en: "St. Gallen",                   zh: "圣加仑",    es: "San Galo",                       pt: "São Galo",                       ru: "Санкт-Галлен"          },
  "Tessin":                    { de: "Tessin",                            gsw: "Tessin",                           fr: "Tessin",                            it: "Ticino",                  en: "Ticino",                       zh: "提契诺",    es: "Tesino",                         pt: "Ticino",                         ru: "Тичино"                },
  "Thurgau":                   { de: "Thurgau",                           gsw: "Thurgau",                          fr: "Thurgovie",                         it: "Turgovia",                en: "Thurgau",                      zh: "图尔高",    es: "Turgovia",                       pt: "Turgovea",                       ru: "Тургау"                },
  "Uri":                       { de: "Uri",                               gsw: "Uri",                              fr: "Uri",                               it: "Uri",                     en: "Uri",                          zh: "乌里",      es: "Uri",                            pt: "Uri",                            ru: "Ури"                   },
  "Waadt":                     { de: "Waadt",                             gsw: "Waadt",                            fr: "Vaud",                              it: "Vaud",                    en: "Vaud",                         zh: "沃州",      es: "Vaud",                           pt: "Vaud",                           ru: "Во"                    },
  "Wallis":                    { de: "Wallis",                            gsw: "Wallis",                           fr: "Valais",                            it: "Vallese",                 en: "Valais",                       zh: "瓦莱",      es: "Valais",                         pt: "Valais",                         ru: "Вале"                  },
  "Zug":                       { de: "Zug",                               gsw: "Zug",                              fr: "Zoug",                              it: "Zugo",                    en: "Zug",                          zh: "楚格",      es: "Zug",                            pt: "Zug",                            ru: "Цуг"                   },
  "Zürich":                    { de: "Zürich",                            gsw: "Züri",                             fr: "Zurich",                            it: "Zurigo",                  en: "Zurich",                       zh: "苏黎世",    es: "Zúrich",                         pt: "Zurique",                        ru: "Цюрих"                 },
};

/**
 * Gibt den Kantonsnamen in der gewünschten Sprache zurück.
 * Fällt auf den deutschen Namen zurück wenn keine Übersetzung vorhanden.
 */
export function translateCanton(germanName: string, lang: LanguageCode): string {
  return CANTON_NAMES[germanName]?.[lang] ?? germanName;
}
