import { createUseStrings, StringsDict } from "./createStrings";

export interface ComponentStrings {
  backToApp: string;
  backToOverview: string;
  fullscreenMap: string;
  closeFullscreen: string;
  details: string;
  arCamera: string;
  terrainProfileLoading: string;
  mapLoading: string;
  satelliteLoading: string;
  terrain3dTitle: string;
  terrain3dUnavailable: string;
  timeline: string;
  pause: string;
  play: string;
  speed: (value: number) => string;
  terrainSurface: string;
}

const STRINGS: StringsDict<ComponentStrings> = {
  de: { backToApp: "Zurück zur App", backToOverview: "Zurück zur Übersicht", fullscreenMap: "Karte im Vollbild anzeigen", closeFullscreen: "Vollbild schliessen", details: "Details", arCamera: "AR-Kamera öffnen", terrainProfileLoading: "Höhenprofil wird geladen", mapLoading: "Karte wird geladen", satelliteLoading: "Satellitenbild wird geladen", terrain3dTitle: "3D-Gelände", terrain3dUnavailable: "Die 3D-Geländeansicht ist auf diesem Gerät ohne native Grafikunterstützung nicht verfügbar.", timeline: "Position in der 3D-Zeitleiste", pause: "Pause", play: "Abspielen", speed: (value) => `Tempo ${value}x`, terrainSurface: "als Geländeoberfläche" },
  gsw: { backToApp: "Zrugg zur App", backToOverview: "Zrugg zur Übersicht", fullscreenMap: "Charte im Vollbild zeige", closeFullscreen: "Vollbild zumache", details: "Details", arCamera: "AR-Kamera öffne", terrainProfileLoading: "Höchi-Profil wird glade", mapLoading: "Charte wird glade", satelliteLoading: "Satellittebild wird glade", terrain3dTitle: "3D-Gelände", terrain3dUnavailable: "D 3D-Geländeansicht isch uf däm Grät ohni nativi Grafikunterstützig nöd verfüegbar.", timeline: "Position i dr 3D-Ziitleiste", pause: "Pause", play: "Abspiele", speed: (value) => `Tempo ${value}x`, terrainSurface: "als Geländeoberflächi" },
  en: { backToApp: "Back to app", backToOverview: "Back to overview", fullscreenMap: "Show map full screen", closeFullscreen: "Close full screen", details: "Details", arCamera: "Open AR camera", terrainProfileLoading: "Loading elevation profile", mapLoading: "Loading map", satelliteLoading: "Loading satellite image", terrain3dTitle: "3D terrain", terrain3dUnavailable: "The 3D terrain view is not available on this device without native graphics support.", timeline: "Position in the 3D timeline", pause: "Pause", play: "Play", speed: (value) => `Speed ${value}x`, terrainSurface: "as terrain surface" },
  fr: { backToApp: "Retour à l’application", backToOverview: "Retour à l’aperçu", fullscreenMap: "Afficher la carte en plein écran", closeFullscreen: "Fermer le plein écran", details: "Détails", arCamera: "Ouvrir la caméra AR", terrainProfileLoading: "Chargement du profil d’altitude", mapLoading: "Chargement de la carte", satelliteLoading: "Chargement de l’image satellite", terrain3dTitle: "Terrain 3D", terrain3dUnavailable: "La vue du terrain 3D n’est pas disponible sur cet appareil sans prise en charge graphique native.", timeline: "Position dans la chronologie 3D", pause: "Pause", play: "Lire", speed: (value) => `Vitesse ${value}x`, terrainSurface: "comme surface du terrain" },
  it: { backToApp: "Torna all’app", backToOverview: "Torna alla panoramica", fullscreenMap: "Mostra la mappa a schermo intero", closeFullscreen: "Chiudi schermo intero", details: "Dettagli", arCamera: "Apri fotocamera AR", terrainProfileLoading: "Caricamento del profilo altimetrico", mapLoading: "Caricamento della mappa", satelliteLoading: "Caricamento dell’immagine satellitare", terrain3dTitle: "Terreno 3D", terrain3dUnavailable: "La vista del terreno 3D non è disponibile su questo dispositivo senza supporto grafico nativo.", timeline: "Posizione nella timeline 3D", pause: "Pausa", play: "Riproduci", speed: (value) => `Velocità ${value}x`, terrainSurface: "come superficie del terreno" },
  es: { backToApp: "Volver a la app", backToOverview: "Volver a la vista general", fullscreenMap: "Mostrar mapa en pantalla completa", closeFullscreen: "Cerrar pantalla completa", details: "Detalles", arCamera: "Abrir cámara AR", terrainProfileLoading: "Cargando perfil de elevación", mapLoading: "Cargando mapa", satelliteLoading: "Cargando imagen satelital", terrain3dTitle: "Terreno 3D", terrain3dUnavailable: "La vista del terreno 3D no está disponible en este dispositivo sin compatibilidad gráfica nativa.", timeline: "Posición en la línea de tiempo 3D", pause: "Pausa", play: "Reproducir", speed: (value) => `Velocidad ${value}x`, terrainSurface: "como superficie del terreno" },
  pt: { backToApp: "Voltar à aplicação", backToOverview: "Voltar à vista geral", fullscreenMap: "Mostrar mapa em ecrã inteiro", closeFullscreen: "Fechar ecrã inteiro", details: "Detalhes", arCamera: "Abrir câmara AR", terrainProfileLoading: "A carregar perfil de elevação", mapLoading: "A carregar mapa", satelliteLoading: "A carregar imagem de satélite", terrain3dTitle: "Terreno 3D", terrain3dUnavailable: "A vista do terreno 3D não está disponível neste dispositivo sem suporte gráfico nativo.", timeline: "Posição na linha temporal 3D", pause: "Pausa", play: "Reproduzir", speed: (value) => `Velocidade ${value}x`, terrainSurface: "como superfície do terreno" },
  zh: { backToApp: "返回应用", backToOverview: "返回概览", fullscreenMap: "全屏显示地图", closeFullscreen: "关闭全屏", details: "详情", arCamera: "打开 AR 相机", terrainProfileLoading: "正在加载海拔剖面", mapLoading: "正在加载地图", satelliteLoading: "正在加载卫星图像", terrain3dTitle: "三维地形", terrain3dUnavailable: "此设备不支持原生图形，无法使用三维地形视图。", timeline: "三维时间轴位置", pause: "暂停", play: "播放", speed: (value) => `速度 ${value}x`, terrainSurface: "作为地形表面" },
  ru: { backToApp: "Назад в приложение", backToOverview: "Назад к обзору", fullscreenMap: "Открыть карту на весь экран", closeFullscreen: "Закрыть полноэкранный режим", details: "Подробнее", arCamera: "Открыть AR-камеру", terrainProfileLoading: "Загрузка профиля высот", mapLoading: "Загрузка карты", satelliteLoading: "Загрузка спутникового снимка", terrain3dTitle: "3D-рельеф", terrain3dUnavailable: "3D-рельеф недоступен на этом устройстве без поддержки нативной графики.", timeline: "Позиция на 3D-шкале времени", pause: "Пауза", play: "Воспроизвести", speed: (value) => `Скорость ${value}x`, terrainSurface: "как поверхность рельефа" },
};

export const useComponentStrings = createUseStrings(STRINGS);

export interface ElevationChartStrings {
  hazardLevel: (level: number) => string;
  avalanche: (level: number) => string;
  snowIce: (height: number) => string;
  thunderstorm: string;
  uv: (level: number) => string;
  fallbackLevel: (level: number) => string;
}

const ELEVATION_CHART_STRINGS: StringsDict<ElevationChartStrings> = {
  de: { hazardLevel: (level) => `Gefahrenstufe ${level} – ${["", "Gering", "Mäßig", "Erheblich", "Groß", "Sehr groß", "Extrem"][level] ?? `Stufe ${level}`}`, avalanche: (level) => `Lawine Stufe ${level}`, snowIce: (height) => `Schnee/Eis ab ${height} m`, thunderstorm: "Gewittergefahr", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Stufe ${level}` },
  gsw: { hazardLevel: (level) => `Gfahrästufe ${level} – ${["", "Chlii", "Mässig", "Erheblich", "Gross", "Sehr gross", "Extrem"][level] ?? `Stufe ${level}`}`, avalanche: (level) => `Lawine-Stufe ${level}`, snowIce: (height) => `Schnee/Iis ab ${height} m`, thunderstorm: "Gwittergfahr", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Stufe ${level}` },
  fr: { hazardLevel: (level) => `Niveau de danger ${level} – ${["", "Faible", "Modéré", "Marqué", "Fort", "Très fort", "Extrême"][level] ?? `Niveau ${level}`}`, avalanche: (level) => `Avalanche niveau ${level}`, snowIce: (height) => `Neige/glace dès ${height} m`, thunderstorm: "Risque d’orage", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Niveau ${level}` },
  it: { hazardLevel: (level) => `Livello di pericolo ${level} – ${["", "Basso", "Moderato", "Marcato", "Forte", "Molto forte", "Estremo"][level] ?? `Livello ${level}`}`, avalanche: (level) => `Valanga livello ${level}`, snowIce: (height) => `Neve/ghiaccio da ${height} m`, thunderstorm: "Rischio temporali", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Livello ${level}` },
  en: { hazardLevel: (level) => `Hazard level ${level} – ${["", "Low", "Moderate", "Considerable", "High", "Very high", "Extreme"][level] ?? `Level ${level}`}`, avalanche: (level) => `Avalanche level ${level}`, snowIce: (height) => `Snow/ice from ${height} m`, thunderstorm: "Thunderstorm risk", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Level ${level}` },
  zh: { hazardLevel: (level) => `危险等级 ${level} – ${["", "低", "中等", "较高", "高", "很高", "极高"][level] ?? `等级 ${level}`}`, avalanche: (level) => `雪崩等级 ${level}`, snowIce: (height) => `${height} 米以上有雪/冰`, thunderstorm: "雷暴风险", uv: (level) => `紫外线 ${level}`, fallbackLevel: (level) => `等级 ${level}` },
  es: { hazardLevel: (level) => `Nivel de peligro ${level} – ${["", "Bajo", "Moderado", "Considerable", "Alto", "Muy alto", "Extremo"][level] ?? `Nivel ${level}`}`, avalanche: (level) => `Avalancha nivel ${level}`, snowIce: (height) => `Nieve/hielo desde ${height} m`, thunderstorm: "Riesgo de tormenta", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Nivel ${level}` },
  pt: { hazardLevel: (level) => `Nível de perigo ${level} – ${["", "Baixo", "Moderado", "Considerável", "Alto", "Muito alto", "Extremo"][level] ?? `Nível ${level}`}`, avalanche: (level) => `Avalanche nível ${level}`, snowIce: (height) => `Neve/gelo a partir de ${height} m`, thunderstorm: "Risco de trovoada", uv: (level) => `UV ${level}`, fallbackLevel: (level) => `Nível ${level}` },
  ru: { hazardLevel: (level) => `Уровень опасности ${level} — ${["", "Низкий", "Умеренный", "Значительный", "Высокий", "Очень высокий", "Экстремальный"][level] ?? `Уровень ${level}`}`, avalanche: (level) => `Лавина, уровень ${level}`, snowIce: (height) => `Снег/лёд от ${height} м`, thunderstorm: "Опасность грозы", uv: (level) => `УФ ${level}`, fallbackLevel: (level) => `Уровень ${level}` },
};

export const useElevationChartStrings = createUseStrings(ELEVATION_CHART_STRINGS);

export interface TerrainAccessibilityStrings {
  gradeCalculating: string;
  gradeUphill: (percent: number) => string;
  gradeDownhill: (percent: number) => string;
  gradeFlat: string;
  gradeMetric: string;
  missingData: string;
  satelliteError: string;
  graphicsUnavailable: string;
  terrainError: string;
  noElevationEstimate: string;
  preparing: string;
  satelliteLoading: string;
  walkedDistance: string;
  elevationGain: string;
  walkingTime: string;
}

const TERRAIN_ACCESSIBILITY_STRINGS: StringsDict<TerrainAccessibilityStrings> = {
  de: { gradeCalculating: "Neigung wird berechnet", gradeUphill: (p) => `Steigung ${p} Prozent`, gradeDownhill: (p) => `Gefälle ${p} Prozent`, gradeFlat: "Ebene Route, 0 Prozent", gradeMetric: "Neigung", missingData: "Für diese Route fehlen die benötigten Geländedaten.", satelliteError: "Die Satellitenkarte konnte nicht geladen werden.", graphicsUnavailable: "Die native 3D-Grafik ist auf diesem Gerät nicht verfügbar.", terrainError: "Das 3D-Gelände konnte nicht geladen werden.", noElevationEstimate: "Es werden keine Höhenwerte geschätzt.", preparing: "3D-Grafik wird vorbereitet …", satelliteLoading: "Satellitenkarte wird geladen …", walkedDistance: "Gegangene Distanz", elevationGain: "Höhenmeter", walkingTime: "Gehzeit" },
  gsw: { gradeCalculating: "Neigig wird berechnet", gradeUphill: (p) => `Stäägig ${p} Prozänt`, gradeDownhill: (p) => `Gfälle ${p} Prozänt`, gradeFlat: "Ebeni Route, 0 Prozänt", gradeMetric: "Neigig", missingData: "Für die Route fähled d nötige Geländedate.", satelliteError: "D Satellittecharte hät nöd chönne glade werde.", graphicsUnavailable: "D native 3D-Grafik isch uf däm Grät nöd verfüegbar.", terrainError: "S 3D-Gelände hät nöd chönne glade werde.", noElevationEstimate: "Es werde kei Höchewärt gschätzt.", preparing: "3D-Grafik wird vorbereitet …", satelliteLoading: "Satellittecharte wird glade …", walkedDistance: "Gwanderti Distanz", elevationGain: "Höchemeter", walkingTime: "Wanderziit" },
  fr: { gradeCalculating: "Calcul de la pente", gradeUphill: (p) => `Montée ${p} pour cent`, gradeDownhill: (p) => `Descente ${p} pour cent`, gradeFlat: "Itinéraire plat, 0 pour cent", gradeMetric: "Pente", missingData: "Les données de terrain nécessaires manquent pour cet itinéraire.", satelliteError: "La carte satellite n’a pas pu être chargée.", graphicsUnavailable: "Les graphismes 3D natifs ne sont pas disponibles sur cet appareil.", terrainError: "Le terrain 3D n’a pas pu être chargé.", noElevationEstimate: "Aucune altitude n’est estimée.", preparing: "Préparation des graphismes 3D…", satelliteLoading: "Chargement de la carte satellite…", walkedDistance: "Distance parcourue", elevationGain: "Dénivelé", walkingTime: "Durée de marche" },
  it: { gradeCalculating: "Calcolo della pendenza", gradeUphill: (p) => `Salita ${p} percento`, gradeDownhill: (p) => `Discesa ${p} percento`, gradeFlat: "Percorso pianeggiante, 0 percento", gradeMetric: "Pendenza", missingData: "Mancano i dati del terreno necessari per questo percorso.", satelliteError: "Impossibile caricare la mappa satellitare.", graphicsUnavailable: "La grafica 3D nativa non è disponibile su questo dispositivo.", terrainError: "Impossibile caricare il terreno 3D.", noElevationEstimate: "Nessuna quota stimata.", preparing: "Preparazione della grafica 3D…", satelliteLoading: "Caricamento della mappa satellitare…", walkedDistance: "Distanza percorsa", elevationGain: "Dislivello", walkingTime: "Tempo di cammino" },
  en: { gradeCalculating: "Calculating incline", gradeUphill: (p) => `Uphill ${p} percent`, gradeDownhill: (p) => `Downhill ${p} percent`, gradeFlat: "Flat route, 0 percent", gradeMetric: "Incline", missingData: "The terrain data required for this route is missing.", satelliteError: "The satellite map could not be loaded.", graphicsUnavailable: "Native 3D graphics are not available on this device.", terrainError: "The 3D terrain could not be loaded.", noElevationEstimate: "No elevation values are estimated.", preparing: "Preparing 3D graphics…", satelliteLoading: "Loading satellite map…", walkedDistance: "Distance walked", elevationGain: "Elevation gain", walkingTime: "Walking time" },
  zh: { gradeCalculating: "正在计算坡度", gradeUphill: (p) => `上坡 ${p}%`, gradeDownhill: (p) => `下坡 ${p}%`, gradeFlat: "平坦路线，0%", gradeMetric: "坡度", missingData: "此路线缺少所需的地形数据。", satelliteError: "无法加载卫星地图。", graphicsUnavailable: "此设备不支持原生三维图形。", terrainError: "无法加载三维地形。", noElevationEstimate: "未估算海拔数据。", preparing: "正在准备三维图形…", satelliteLoading: "正在加载卫星地图…", walkedDistance: "已行走距离", elevationGain: "爬升高度", walkingTime: "行走时间" },
  es: { gradeCalculating: "Calculando la pendiente", gradeUphill: (p) => `Subida ${p} por ciento`, gradeDownhill: (p) => `Bajada ${p} por ciento`, gradeFlat: "Ruta llana, 0 por ciento", gradeMetric: "Pendiente", missingData: "Faltan los datos de terreno necesarios para esta ruta.", satelliteError: "No se pudo cargar el mapa satelital.", graphicsUnavailable: "Los gráficos 3D nativos no están disponibles en este dispositivo.", terrainError: "No se pudo cargar el terreno 3D.", noElevationEstimate: "No se estiman valores de altitud.", preparing: "Preparando gráficos 3D…", satelliteLoading: "Cargando mapa satelital…", walkedDistance: "Distancia recorrida", elevationGain: "Desnivel positivo", walkingTime: "Tiempo de marcha" },
  pt: { gradeCalculating: "A calcular a inclinação", gradeUphill: (p) => `Subida ${p} por cento`, gradeDownhill: (p) => `Descida ${p} por cento`, gradeFlat: "Percurso plano, 0 por cento", gradeMetric: "Inclinação", missingData: "Faltam os dados de terreno necessários para este percurso.", satelliteError: "Não foi possível carregar o mapa de satélite.", graphicsUnavailable: "Os gráficos 3D nativos não estão disponíveis neste dispositivo.", terrainError: "Não foi possível carregar o terreno 3D.", noElevationEstimate: "Não são estimados valores de altitude.", preparing: "A preparar os gráficos 3D…", satelliteLoading: "A carregar o mapa de satélite…", walkedDistance: "Distância percorrida", elevationGain: "Desnível positivo", walkingTime: "Tempo de caminhada" },
  ru: { gradeCalculating: "Расчёт уклона", gradeUphill: (p) => `Подъём ${p} процентов`, gradeDownhill: (p) => `Спуск ${p} процентов`, gradeFlat: "Ровный маршрут, 0 процентов", gradeMetric: "Уклон", missingData: "Для этого маршрута отсутствуют необходимые данные о рельефе.", satelliteError: "Не удалось загрузить спутниковую карту.", graphicsUnavailable: "На этом устройстве недоступна нативная 3D-графика.", terrainError: "Не удалось загрузить 3D-рельеф.", noElevationEstimate: "Высота не оценивается.", preparing: "Подготовка 3D-графики…", satelliteLoading: "Загрузка спутниковой карты…", walkedDistance: "Пройденное расстояние", elevationGain: "Набор высоты", walkingTime: "Время в пути" },
};

export const useTerrainAccessibilityStrings = createUseStrings(TERRAIN_ACCESSIBILITY_STRINGS);

export interface ExtendedComponentStrings {
  watchTitle: string; watchActive: string; watchDenied: string; watchChecking: string;
  watchDirection: string; watchRemaining: string; watchHint: string;
  completionTitle: string; chapter: string; completionHint: string;
  sosGpsRequired: string; sosNoContact: string;
  virtualEyebrow: string; virtualTitle: string; virtualSubtitle: string;
  more: string; less: string; sourceWikipedia: string;
  partnerCategories: Record<string, string>;
}

const EXTENDED: StringsDict<ExtendedComponentStrings> = {
  de: { watchTitle:"Watch-Begleitung",watchActive:"Watch-Verbindung aktiv",watchDenied:"Watch-Mitteilungen nicht erlaubt",watchChecking:"Watch-Begleitung wird geprüft",watchDirection:"Richtung",watchRemaining:"Rest",watchHint:"Nur Abbiegehinweise und SOS werden als native Mitteilungen auf die gekoppelte Watch gespiegelt. Regelmässige Status-Pushes mit Richtung oder Distanz sind deaktiviert.",completionTitle:"Wanderung abgeschlossen",chapter:"Kapitel",completionHint:"Speichere jetzt deine persönliche Zusammenfassung mit Route, Sagen und Erlebnissen.",sosGpsRequired:"Eine aktuelle GPS-Position ist erforderlich, bevor dein Standort geteilt werden kann.",sosNoContact:"Bitte hinterlege zuerst einen Notfallkontakt.",virtualEyebrow:"3D-ROUTE",virtualTitle:"Diese Route virtuell ansehen",virtualSubtitle:"Erkunde die Landschaft entlang deiner Route in 3D.",more:"Mehr anzeigen",less:"Weniger anzeigen",sourceWikipedia:"Quelle: Wikipedia",partnerCategories:{restaurant:"Restaurant",cafe:"Café",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Shop",default:"Partnerbetrieb"} },
  gsw: { watchTitle:"Watch-Begleitig",watchActive:"Watch-Verbindig aktiv",watchDenied:"Watch-Mitteilige nöd erlaubt",watchChecking:"Watch-Begleitig wird prüeft",watchDirection:"Richtig",watchRemaining:"Räscht",watchHint:"Nume Abzwiigige und SOS wärde als nativi Mitteilige uf d verbundeni Watch gspiegelt. Regelmässigi Status-Pushes mit Richtig oder Distanz sind deaktiviert.",completionTitle:"Wanderig abgschlosse",chapter:"Kapitel",completionHint:"Speicher jetzt dini persönlechi Zämefassig mit Route, Sage und Erläbnis.",sosGpsRequired:"E aktuelli GPS-Position isch nötig, bevor din Standort chann teilt werde.",sosNoContact:"Bitte hinterleg zerscht en Notfallkontakt.",virtualEyebrow:"3D-ROUTE",virtualTitle:"Die Route virtuell aluege",virtualSubtitle:"Entdeck d Landschaft vo diner Route i 3D.",more:"Meh aazeige",less:"Weniger aazeige",sourceWikipedia:"Quelle: Wikipedia",partnerCategories:{restaurant:"Restaurant",cafe:"Café",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Shop",default:"Partnerbetrieb"} },
  en: { watchTitle:"Watch companion",watchActive:"Watch connection active",watchDenied:"Watch notifications not allowed",watchChecking:"Checking Watch companion",watchDirection:"Direction",watchRemaining:"Remaining",watchHint:"Only turn guidance and SOS are mirrored as native notifications to the paired Watch. Regular status pushes with direction or distance are disabled.",completionTitle:"Hike completed",chapter:"Chapters",completionHint:"Save your personal summary with route, legends and experiences.",sosGpsRequired:"A current GPS position is required before your location can be shared.",sosNoContact:"Please add an emergency contact first.",virtualEyebrow:"3D ROUTE",virtualTitle:"Explore this route virtually",virtualSubtitle:"Explore the landscape along your route in 3D.",more:"Show more",less:"Show less",sourceWikipedia:"Source: Wikipedia",partnerCategories:{restaurant:"Restaurant",cafe:"Café",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Shop",default:"Partner business"} },
  fr: { watchTitle:"Compagnon Watch",watchActive:"Connexion Watch active",watchDenied:"Notifications Watch non autorisées",watchChecking:"Vérification du compagnon Watch",watchDirection:"Direction",watchRemaining:"Restant",watchHint:"Seuls les indications de virage et le SOS sont transmis comme notifications natives à la Watch associée. Les mises à jour régulières sont désactivées.",completionTitle:"Randonnée terminée",chapter:"Chapitres",completionHint:"Enregistrez maintenant votre résumé personnel avec itinéraire, légendes et expériences.",sosGpsRequired:"Une position GPS actuelle est nécessaire avant de partager votre position.",sosNoContact:"Ajoutez d’abord un contact d’urgence.",virtualEyebrow:"ITINÉRAIRE 3D",virtualTitle:"Explorer cet itinéraire virtuellement",virtualSubtitle:"Explorez le paysage de votre itinéraire en 3D.",more:"Afficher plus",less:"Afficher moins",sourceWikipedia:"Source : Wikipédia",partnerCategories:{restaurant:"Restaurant",cafe:"Café",bar:"Bar",hotel:"Hôtel",uebernachtung:"Hôtel",shop:"Boutique",default:"Établissement partenaire"} },
  it: { watchTitle:"Compagno Watch",watchActive:"Connessione Watch attiva",watchDenied:"Notifiche Watch non consentite",watchChecking:"Verifica del compagno Watch",watchDirection:"Direzione",watchRemaining:"Rimanente",watchHint:"Solo indicazioni di svolta e SOS vengono inviati come notifiche native alla Watch associata. Gli aggiornamenti regolari sono disattivati.",completionTitle:"Escursione completata",chapter:"Capitoli",completionHint:"Salva ora il tuo riepilogo personale con percorso, leggende ed esperienze.",sosGpsRequired:"È necessaria una posizione GPS attuale prima di condividere la tua posizione.",sosNoContact:"Aggiungi prima un contatto d’emergenza.",virtualEyebrow:"PERCORSO 3D",virtualTitle:"Esplora virtualmente questo percorso",virtualSubtitle:"Esplora il paesaggio del percorso in 3D.",more:"Mostra altro",less:"Mostra meno",sourceWikipedia:"Fonte: Wikipedia",partnerCategories:{restaurant:"Ristorante",cafe:"Caffè",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Negozio",default:"Struttura partner"} },
  es: { watchTitle:"Compañero Watch",watchActive:"Conexión Watch activa",watchDenied:"Notificaciones de Watch no permitidas",watchChecking:"Comprobando compañero Watch",watchDirection:"Dirección",watchRemaining:"Restante",watchHint:"Solo las indicaciones de giro y SOS se reflejan como notificaciones nativas en el Watch asociado. Las actualizaciones periódicas están desactivadas.",completionTitle:"Excursión completada",chapter:"Capítulos",completionHint:"Guarda ahora tu resumen personal con ruta, leyendas y experiencias.",sosGpsRequired:"Se necesita una posición GPS actual antes de compartir tu ubicación.",sosNoContact:"Añade primero un contacto de emergencia.",virtualEyebrow:"RUTA 3D",virtualTitle:"Explorar esta ruta virtualmente",virtualSubtitle:"Explora el paisaje de tu ruta en 3D.",more:"Mostrar más",less:"Mostrar menos",sourceWikipedia:"Fuente: Wikipedia",partnerCategories:{restaurant:"Restaurante",cafe:"Café",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Tienda",default:"Establecimiento asociado"} },
  pt: { watchTitle:"Companheiro Watch",watchActive:"Ligação Watch ativa",watchDenied:"Notificações Watch não permitidas",watchChecking:"A verificar companheiro Watch",watchDirection:"Direção",watchRemaining:"Restante",watchHint:"Apenas as indicações de mudança de direção e SOS são refletidas como notificações nativas no Watch associado. As atualizações regulares estão desativadas.",completionTitle:"Caminhada concluída",chapter:"Capítulos",completionHint:"Guarde agora o seu resumo pessoal com percurso, lendas e experiências.",sosGpsRequired:"É necessária uma posição GPS atual antes de partilhar a sua localização.",sosNoContact:"Adicione primeiro um contacto de emergência.",virtualEyebrow:"PERCURSO 3D",virtualTitle:"Explorar este percurso virtualmente",virtualSubtitle:"Explore a paisagem do seu percurso em 3D.",more:"Mostrar mais",less:"Mostrar menos",sourceWikipedia:"Fonte: Wikipédia",partnerCategories:{restaurant:"Restaurante",cafe:"Café",bar:"Bar",hotel:"Hotel",uebernachtung:"Hotel",shop:"Loja",default:"Estabelecimento parceiro"} },
  zh: { watchTitle:"手表助手",watchActive:"手表连接已启用",watchDenied:"不允许手表通知",watchChecking:"正在检查手表助手",watchDirection:"方向",watchRemaining:"剩余",watchHint:"只有转弯指引和 SOS 会作为原生通知发送到已配对的手表。定期状态推送已停用。",completionTitle:"徒步完成",chapter:"章节",completionHint:"立即保存包含路线、传说和体验的个人总结。",sosGpsRequired:"分享位置前需要最新的 GPS 定位。",sosNoContact:"请先添加紧急联系人。",virtualEyebrow:"三维路线",virtualTitle:"虚拟查看此路线",virtualSubtitle:"以三维方式探索路线沿途的景观。",more:"显示更多",less:"显示更少",sourceWikipedia:"来源：维基百科",partnerCategories:{restaurant:"餐厅",cafe:"咖啡馆",bar:"酒吧",hotel:"酒店",uebernachtung:"酒店",shop:"商店",default:"合作商家"} },
  ru: { watchTitle:"Спутник Watch",watchActive:"Watch подключены",watchDenied:"Уведомления Watch запрещены",watchChecking:"Проверка спутника Watch",watchDirection:"Направление",watchRemaining:"Осталось",watchHint:"На подключённые Watch отправляются только уведомления о поворотах и SOS. Регулярные обновления статуса отключены.",completionTitle:"Поход завершён",chapter:"Главы",completionHint:"Сохраните личное резюме с маршрутом, легендами и впечатлениями.",sosGpsRequired:"Перед отправкой местоположения требуется свежая GPS-позиция.",sosNoContact:"Сначала добавьте экстренный контакт.",virtualEyebrow:"3D-МАРШРУТ",virtualTitle:"Виртуальный просмотр маршрута",virtualSubtitle:"Исследуйте ландшафт маршрута в 3D.",more:"Показать больше",less:"Показать меньше",sourceWikipedia:"Источник: Википедия",partnerCategories:{restaurant:"Ресторан",cafe:"Кафе",bar:"Бар",hotel:"Отель",uebernachtung:"Отель",shop:"Магазин",default:"Партнёрское заведение"} },
};

export const useExtendedComponentStrings = createUseStrings(EXTENDED);