// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ar-route/Current.tsx": () => import("../components/mockups/ar-route/Current.tsx"),
  "./components/mockups/ar-route/Guidance.tsx": () => import("../components/mockups/ar-route/Guidance.tsx"),
  "./components/mockups/garmin-watch-redesign/Current.tsx": () => import("../components/mockups/garmin-watch-redesign/Current.tsx"),
  "./components/mockups/garmin-watch-redesign/Horizon.tsx": () => import("../components/mockups/garmin-watch-redesign/Horizon.tsx"),
  "./components/mockups/garmin-watch-redesign/Instrument.tsx": () => import("../components/mockups/garmin-watch-redesign/Instrument.tsx"),
  "./components/mockups/garmin-watch-redesign/Wayfinder.tsx": () => import("../components/mockups/garmin-watch-redesign/Wayfinder.tsx"),
  "./components/mockups/route-card-info/GlasChips.tsx": () => import("../components/mockups/route-card-info/GlasChips.tsx"),
  "./components/mockups/route-card-info/ZeitAufSchild.tsx": () => import("../components/mockups/route-card-info/ZeitAufSchild.tsx"),
  "./components/mockups/route-card-info/Zeitleiste.tsx": () => import("../components/mockups/route-card-info/Zeitleiste.tsx"),
  "./components/mockups/route-card-info/Zusatztafel.tsx": () => import("../components/mockups/route-card-info/Zusatztafel.tsx"),
  "./components/mockups/route-detail/BeatusCard.tsx": () => import("../components/mockups/route-detail/BeatusCard.tsx"),
  "./components/mockups/route-detail/RigiCard.tsx": () => import("../components/mockups/route-detail/RigiCard.tsx"),
  "./components/mockups/route-detail/RouteDunkel.tsx": () => import("../components/mockups/route-detail/RouteDunkel.tsx"),
  "./components/mockups/route-detail/RouteHell.tsx": () => import("../components/mockups/route-detail/RouteHell.tsx"),
  "./components/mockups/route-detail/StoosCard.tsx": () => import("../components/mockups/route-detail/StoosCard.tsx"),
  "./components/mockups/social-card/SocialCard.tsx": () => import("../components/mockups/social-card/SocialCard.tsx"),
  "./components/mockups/social-card/WalserCard.tsx": () => import("../components/mockups/social-card/WalserCard.tsx"),
  "./components/mockups/sagatrail-theme/SchweizDunkel.tsx": () => import("../components/mockups/sagatrail-theme/SchweizDunkel.tsx"),
  "./components/mockups/sagatrail-theme/SchweizHell.tsx": () => import("../components/mockups/sagatrail-theme/SchweizHell.tsx")
};
