// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sagatrail-theme/SchweizDunkel.tsx": () => import("../components/mockups/sagatrail-theme/SchweizDunkel.tsx"),
  "./components/mockups/sagatrail-theme/SchweizHell.tsx": () => import("../components/mockups/sagatrail-theme/SchweizHell.tsx")
};
